version: 3

tasks:
  dev:
    cmds:
      - npm start

  deploy:
    cmds:
      - DEPLOYMENT_BRANCH=gh-pages USE_SSH=true yarn deploy

  ###########################################################################

  push:
    cmds:
      - git push origin main --tags
      - repo_url=`git remote -v | grep push | awk -F ":" '{print $2}' | awk -F ".git " '{print "https://github.com/"$1}'`; open $repo_url ; echo $repo_url;
